/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;
//etest

import javax.swing.JOptionPane;
import oodj_assignment_functions.Administrator;

/**
 *
 * @author Lenovo
 */
public class AM_MainForm extends javax.swing.JFrame {
    static String name;
    static String role;
    static String uid;
    
    Administrator adm = new Administrator();
    public AM_MainForm(String name, String role) {
        initComponents();
        this.name = name;
        this.role = role;
    }
    public AM_MainForm()
    {
       initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AM_FunctionPanel = new javax.swing.JPanel();
        AM_ManageUser = new javax.swing.JButton();
        AM_LogOutBtn = new javax.swing.JButton();
        AM_AccessPM = new javax.swing.JButton();
        AM_AccessSM = new javax.swing.JButton();
        AM_AccessIM = new javax.swing.JButton();
        AM_AccessFM = new javax.swing.JButton();
        AM_GreetingLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AM_Table = new javax.swing.JTable();
        AM_EditUser = new javax.swing.JButton();
        AM_RegisterUser = new javax.swing.JButton();
        AM_DeleteUser = new javax.swing.JButton();
        AM_UIDlbl = new javax.swing.JLabel();
        AM_UID = new javax.swing.JLabel();
        AM_NameLbl = new javax.swing.JLabel();
        AM_username = new javax.swing.JTextField();
        AM_PassLbl = new javax.swing.JLabel();
        AM_password = new javax.swing.JTextField();
        AM_RoleLbl = new javax.swing.JLabel();
        AM_RolesCmbx = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("AdministratorForm"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1050, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setName("Administrator Panel"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 550));

        AM_FunctionPanel.setBackground(new java.awt.Color(204, 204, 204));
        AM_FunctionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Administrator Functionalities", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N
        AM_FunctionPanel.setToolTipText("");
        AM_FunctionPanel.setPreferredSize(new java.awt.Dimension(250, 499));

        AM_ManageUser.setBackground(new java.awt.Color(153, 153, 153));
        AM_ManageUser.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_ManageUser.setText("Manage User");
        AM_ManageUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_ManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_ManageUserActionPerformed(evt);
            }
        });

        AM_LogOutBtn.setBackground(new java.awt.Color(102, 102, 102));
        AM_LogOutBtn.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_LogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment_images/logout.png"))); // NOI18N
        AM_LogOutBtn.setText("Log Out");
        AM_LogOutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_LogOutBtnActionPerformed(evt);
            }
        });

        AM_AccessPM.setBackground(new java.awt.Color(153, 153, 153));
        AM_AccessPM.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_AccessPM.setText("Purchase Manager Functions");
        AM_AccessPM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_AccessPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_AccessPMActionPerformed(evt);
            }
        });

        AM_AccessSM.setBackground(new java.awt.Color(153, 153, 153));
        AM_AccessSM.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_AccessSM.setText("Sales Manager Functions");
        AM_AccessSM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_AccessSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_AccessSMActionPerformed(evt);
            }
        });

        AM_AccessIM.setBackground(new java.awt.Color(153, 153, 153));
        AM_AccessIM.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_AccessIM.setText("Inventory Manager Functions");
        AM_AccessIM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_AccessIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_AccessIMActionPerformed(evt);
            }
        });

        AM_AccessFM.setBackground(new java.awt.Color(153, 153, 153));
        AM_AccessFM.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_AccessFM.setText("Finance Manager Functions");
        AM_AccessFM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_AccessFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_AccessFMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AM_FunctionPanelLayout = new javax.swing.GroupLayout(AM_FunctionPanel);
        AM_FunctionPanel.setLayout(AM_FunctionPanelLayout);
        AM_FunctionPanelLayout.setHorizontalGroup(
            AM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AM_FunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AM_ManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(AM_LogOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AM_AccessPM, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(AM_AccessSM, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(AM_AccessIM, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(AM_AccessFM, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap())
        );
        AM_FunctionPanelLayout.setVerticalGroup(
            AM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AM_FunctionPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AM_ManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AM_AccessSM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AM_AccessPM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AM_AccessIM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AM_AccessFM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AM_LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        AM_GreetingLbl.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        AM_GreetingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AM_GreetingLbl.setText("Welcome, Administrator");
        AM_GreetingLbl.setToolTipText("");
        AM_GreetingLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AM_GreetingLbl.setMaximumSize(new java.awt.Dimension(1050, 50));
        AM_GreetingLbl.setMinimumSize(new java.awt.Dimension(1050, 50));
        AM_GreetingLbl.setName("Welcome Message"); // NOI18N
        AM_GreetingLbl.setPreferredSize(new java.awt.Dimension(1050, 50));

        AM_Table.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AM_Table.setShowGrid(true);
        AM_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AM_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AM_Table);

        AM_EditUser.setBackground(new java.awt.Color(204, 204, 204));
        AM_EditUser.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_EditUser.setText("Edit User");
        AM_EditUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_EditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_EditUserActionPerformed(evt);
            }
        });

        AM_RegisterUser.setBackground(new java.awt.Color(204, 204, 204));
        AM_RegisterUser.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_RegisterUser.setText("Register a User");
        AM_RegisterUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_RegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_RegisterUserActionPerformed(evt);
            }
        });

        AM_DeleteUser.setBackground(new java.awt.Color(204, 204, 204));
        AM_DeleteUser.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        AM_DeleteUser.setText("Delete User");
        AM_DeleteUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AM_DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_DeleteUserActionPerformed(evt);
            }
        });

        AM_UIDlbl.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_UIDlbl.setText("UID: ");

        AM_UID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_UID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        AM_NameLbl.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_NameLbl.setText("Username");

        AM_username.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AM_usernameActionPerformed(evt);
            }
        });

        AM_PassLbl.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_PassLbl.setText("Password");

        AM_password.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        AM_RoleLbl.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_RoleLbl.setText("Role");

        AM_RolesCmbx.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        AM_RolesCmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sales Manager", "Purchase Manager", "Inventory Manager", "Finance Manager", "Administrator" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(AM_FunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AM_RegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AM_EditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(AM_DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AM_RoleLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AM_RolesCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AM_PassLbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AM_UIDlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AM_UID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AM_NameLbl)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AM_password, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(AM_username))
                        .addGap(267, 267, 267))))
            .addComponent(AM_GreetingLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(AM_GreetingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(AM_FunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AM_UIDlbl)
                            .addComponent(AM_UID)
                            .addComponent(AM_NameLbl)
                            .addComponent(AM_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AM_RoleLbl)
                            .addComponent(AM_RolesCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AM_PassLbl)
                            .addComponent(AM_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AM_RegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AM_EditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AM_DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AM_ManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_ManageUserActionPerformed
        if(adm.getIDfromName(name) != null)
        {
            uid = adm.getIDfromName(name);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "fail to get id");
            this.dispose();
            new LoginForm().setVisible(true);
        }
        AM_RegisterUser.setVisible(true);
        AM_EditUser.setVisible(true);
        AM_DeleteUser.setVisible(true);
        AM_UIDlbl.setVisible(true);
        AM_RoleLbl.setVisible(true);
        AM_NameLbl.setVisible(true);
        AM_PassLbl.setVisible(true);
        AM_UID.setVisible(true);
        AM_RolesCmbx.setVisible(true);
        AM_username.setVisible(true);
        AM_password.setVisible(true);
    }//GEN-LAST:event_AM_ManageUserActionPerformed

    private void AM_LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_LogOutBtnActionPerformed
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_AM_LogOutBtnActionPerformed

    private void AM_AccessPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_AccessPMActionPerformed
        this.dispose();
        new PM_MainForm(name).setVisible(true);
    }//GEN-LAST:event_AM_AccessPMActionPerformed

    private void AM_AccessSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_AccessSMActionPerformed
        this.dispose();
        new SM_MainPage().setVisible(true);
    }//GEN-LAST:event_AM_AccessSMActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        AM_GreetingLbl.setText("Welcome, "+ name);
        adm.PopulateUserTable(AM_Table);
        AM_UIDlbl.setVisible(false);
        AM_RoleLbl.setVisible(false);
        AM_NameLbl.setVisible(false);
        AM_PassLbl.setVisible(false);
        AM_UID.setVisible(false);
        AM_RolesCmbx.setVisible(false);
        AM_username.setVisible(false);
        AM_password.setVisible(false);
        AM_RegisterUser.setVisible(false);
        AM_EditUser.setVisible(false);
        AM_DeleteUser.setVisible(false);
    }//GEN-LAST:event_formComponentShown

    private void AM_AccessIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_AccessIMActionPerformed
        this.dispose();
        new IM_MainForm().setVisible(true);
    }//GEN-LAST:event_AM_AccessIMActionPerformed

    private void AM_AccessFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_AccessFMActionPerformed
        this.dispose();
        new FM_MainForm().setVisible(true);
    }//GEN-LAST:event_AM_AccessFMActionPerformed

    private void AM_EditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_EditUserActionPerformed
        if (AM_username.getText().isEmpty() || AM_password.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Click a row in the table to fill in what to modify");
            return;
        }
        if (role.equalsIgnoreCase("Administrator") && !"Administrator".equals(AM_RolesCmbx.getSelectedItem()) && AM_UID.getText().equals(adm.getIDfromName(name)))
        {
            JOptionPane.showMessageDialog(this, "Administrators cannot change their own role!");
            AM_RolesCmbx.setSelectedItem("Administrator"); //Reset combo box to Administrator
        } 
        else 
        {
            adm.EditUser(AM_UID.getText(),AM_username.getText(),AM_password.getText(),String.valueOf(AM_RolesCmbx.getSelectedItem()));
            adm.PopulateUserTable(AM_Table);
        }
    }//GEN-LAST:event_AM_EditUserActionPerformed

    private void AM_RegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_RegisterUserActionPerformed
        String un = AM_username.getText();
        String pw = AM_password.getText();
        if(un.isEmpty()||pw.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please Fill in Name and Password!!!!!");
        }
        else
        {
            if(!adm.DuplicateChecker(un))
            {
                adm.RegisterUser(adm.GenerateID(), un, pw, String.valueOf(AM_RolesCmbx.getSelectedItem()));
                AM_username.setText("");
                AM_password.setText("");
                adm.PopulateUserTable(AM_Table);
            }
        }
    }//GEN-LAST:event_AM_RegisterUserActionPerformed

    private void AM_DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_DeleteUserActionPerformed
        if (AM_UID.getText().isEmpty() || AM_username.getText().isEmpty() || AM_password.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Click a row in the table to fill in what to delete");
            return;
        }
        // Prevent admin from deleting their own role
        if ("Administrator".equalsIgnoreCase(String.valueOf(AM_RolesCmbx.getSelectedItem())))
        {
            JOptionPane.showMessageDialog(this, "Administrators cannot delete another Administrator!");
        }
        else
        {
            adm.DeleteUser(AM_UID.getText());
            AM_UID.setText("");
            AM_username.setText("");
            AM_password.setText("");
            adm.PopulateUserTable(AM_Table);
        }
    }//GEN-LAST:event_AM_DeleteUserActionPerformed

    private void AM_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AM_TableMouseClicked
        int selectedRow = AM_Table.getSelectedRow();
        if (selectedRow != -1)//ensure a row is selected 
        {
            //Set the values to the labels, text field, and combo box
            AM_UID.setText(AM_Table.getValueAt(selectedRow, 0).toString());
            AM_username.setText(AM_Table.getValueAt(selectedRow, 1).toString());
            AM_password.setText(AM_Table.getValueAt(selectedRow, 2).toString());
            AM_RolesCmbx.setSelectedItem(AM_Table.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_AM_TableMouseClicked

    private void AM_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AM_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AM_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AM_MainForm(name, role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AM_AccessFM;
    private javax.swing.JButton AM_AccessIM;
    private javax.swing.JButton AM_AccessPM;
    private javax.swing.JButton AM_AccessSM;
    private javax.swing.JButton AM_DeleteUser;
    private javax.swing.JButton AM_EditUser;
    private javax.swing.JPanel AM_FunctionPanel;
    private javax.swing.JLabel AM_GreetingLbl;
    private javax.swing.JButton AM_LogOutBtn;
    private javax.swing.JButton AM_ManageUser;
    private javax.swing.JLabel AM_NameLbl;
    private javax.swing.JLabel AM_PassLbl;
    private javax.swing.JButton AM_RegisterUser;
    private javax.swing.JLabel AM_RoleLbl;
    private javax.swing.JComboBox<String> AM_RolesCmbx;
    private javax.swing.JTable AM_Table;
    private javax.swing.JLabel AM_UID;
    private javax.swing.JLabel AM_UIDlbl;
    private javax.swing.JTextField AM_password;
    private javax.swing.JTextField AM_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}