/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;
/**
 *
 * @author xiang
 */
public class FM_MainForm extends javax.swing.JFrame {

    /**
     * Creates new form testing
     */
    public FM_MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AM_FunctionPanel = new javax.swing.JPanel();
        FM_StockStatus = new javax.swing.JButton();
        FM_SupplierPaymentStatus = new javax.swing.JButton();
        FM_VerifyOrder = new javax.swing.JButton();
        FM_MakePayment = new javax.swing.JButton();
        MenuBack = new javax.swing.JButton();
        FM_GreetingLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 550));

        AM_FunctionPanel.setBackground(new java.awt.Color(204, 204, 0));
        AM_FunctionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Finance Manager Functionalities", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N
        AM_FunctionPanel.setForeground(new java.awt.Color(0, 0, 0));
        AM_FunctionPanel.setToolTipText("");
        AM_FunctionPanel.setPreferredSize(new java.awt.Dimension(250, 499));

        FM_StockStatus.setBackground(new java.awt.Color(204, 255, 51));
        FM_StockStatus.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        FM_StockStatus.setForeground(new java.awt.Color(0, 0, 0));
        FM_StockStatus.setText("Stock Status");
        FM_StockStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FM_StockStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM_StockStatusActionPerformed(evt);
            }
        });

        FM_SupplierPaymentStatus.setBackground(new java.awt.Color(204, 255, 51));
        FM_SupplierPaymentStatus.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        FM_SupplierPaymentStatus.setForeground(new java.awt.Color(0, 0, 0));
        FM_SupplierPaymentStatus.setText("Supplier Payment Status");
        FM_SupplierPaymentStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FM_SupplierPaymentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM_SupplierPaymentStatusActionPerformed(evt);
            }
        });

        FM_VerifyOrder.setBackground(new java.awt.Color(204, 255, 51));
        FM_VerifyOrder.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        FM_VerifyOrder.setForeground(new java.awt.Color(0, 0, 0));
        FM_VerifyOrder.setText("Verify Purchase Order");
        FM_VerifyOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FM_VerifyOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM_VerifyOrderActionPerformed(evt);
            }
        });

        FM_MakePayment.setBackground(new java.awt.Color(204, 255, 51));
        FM_MakePayment.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        FM_MakePayment.setForeground(new java.awt.Color(0, 0, 0));
        FM_MakePayment.setText("Make Payment");
        FM_MakePayment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FM_MakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM_MakePaymentActionPerformed(evt);
            }
        });

        MenuBack.setText("Back");
        MenuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AM_FunctionPanelLayout = new javax.swing.GroupLayout(AM_FunctionPanel);
        AM_FunctionPanel.setLayout(AM_FunctionPanelLayout);
        AM_FunctionPanelLayout.setHorizontalGroup(
            AM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AM_FunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FM_StockStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FM_SupplierPaymentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                    .addComponent(FM_VerifyOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FM_MakePayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(AM_FunctionPanelLayout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(MenuBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AM_FunctionPanelLayout.setVerticalGroup(
            AM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AM_FunctionPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(FM_VerifyOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(FM_StockStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(FM_MakePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(FM_SupplierPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(MenuBack)
                .addGap(34, 34, 34))
        );

        FM_GreetingLbl.setBackground(new java.awt.Color(204, 255, 153));
        FM_GreetingLbl.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        FM_GreetingLbl.setForeground(new java.awt.Color(0, 0, 0));
        FM_GreetingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FM_GreetingLbl.setText("Finance Manager");
        FM_GreetingLbl.setToolTipText("");
        FM_GreetingLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FM_GreetingLbl.setMaximumSize(new java.awt.Dimension(1050, 50));
        FM_GreetingLbl.setMinimumSize(new java.awt.Dimension(1050, 50));
        FM_GreetingLbl.setName("Welcome Message"); // NOI18N
        FM_GreetingLbl.setPreferredSize(new java.awt.Dimension(1050, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FM_GreetingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(AM_FunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(FM_GreetingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AM_FunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AM_FunctionPanel.getAccessibleContext().setAccessibleName("Finance Manager Functionalities ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, 532, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FM_StockStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM_StockStatusActionPerformed
        // TODO add your handling code here:
        FM_StockStatus stockstatus = new FM_StockStatus();
        stockstatus.setVisible(true);
    }//GEN-LAST:event_FM_StockStatusActionPerformed

    private void FM_SupplierPaymentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM_SupplierPaymentStatusActionPerformed
        // TODO add your handling code here:
        FM_SupplierPaymentStatus supplierpaymentstatus = new FM_SupplierPaymentStatus();
        supplierpaymentstatus.setVisible(true);
    }//GEN-LAST:event_FM_SupplierPaymentStatusActionPerformed

    private void FM_VerifyOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM_VerifyOrderActionPerformed
        // TODO add your handling code here:
        FM_VerifyPurchaseOrder verifypurchaseorder = new FM_VerifyPurchaseOrder();
        verifypurchaseorder.setVisible(true);
    }//GEN-LAST:event_FM_VerifyOrderActionPerformed

    private void FM_MakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM_MakePaymentActionPerformed
        // TODO add your handling code here:
        FM_MakePayment makepayment = new FM_MakePayment();
        makepayment.setVisible(true);
    }//GEN-LAST:event_FM_MakePaymentActionPerformed

    private void MenuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBackActionPerformed
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_MenuBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FM_MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AM_FunctionPanel;
    private javax.swing.JLabel FM_GreetingLbl;
    private javax.swing.JButton FM_MakePayment;
    private javax.swing.JButton FM_StockStatus;
    private javax.swing.JButton FM_SupplierPaymentStatus;
    private javax.swing.JButton FM_VerifyOrder;
    private javax.swing.JButton MenuBack;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
