/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import oodj_assignment_functions.Administrator;
import oodj_assignment_functions.Finance;
/**
 *
 * @author xiang
 */
public class FM_VerifyPurchaseOrder extends javax.swing.JFrame {
    static String name;
    
    Finance fn = new Finance();
    public FM_VerifyPurchaseOrder(String name) {
        initComponents();
        this.name = name;
    }

    public FM_VerifyPurchaseOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FM_StockStatus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        FM_GreetingLb2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PO_Table = new javax.swing.JTable();
        ApproveButton = new javax.swing.JButton();
        RejectButton = new javax.swing.JButton();
        PO_Back = new javax.swing.JButton();

        FM_StockStatus.setBackground(new java.awt.Color(204, 255, 51));
        FM_StockStatus.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        FM_StockStatus.setText("Stock Status");
        FM_StockStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FM_StockStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM_StockStatusActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1050, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 550));

        FM_GreetingLb2.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        FM_GreetingLb2.setForeground(new java.awt.Color(0, 0, 0));
        FM_GreetingLb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FM_GreetingLb2.setText("Verify Purchase Order");
        FM_GreetingLb2.setToolTipText("");
        FM_GreetingLb2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FM_GreetingLb2.setMaximumSize(new java.awt.Dimension(1050, 50));
        FM_GreetingLb2.setMinimumSize(new java.awt.Dimension(1050, 50));
        FM_GreetingLb2.setName("Welcome Message"); // NOI18N
        FM_GreetingLb2.setPreferredSize(new java.awt.Dimension(1050, 50));

        PO_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(PO_Table);

        ApproveButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ApproveButton.setText("Approve");
        ApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveButtonActionPerformed(evt);
            }
        });

        RejectButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RejectButton.setText("Reject");
        RejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectButtonActionPerformed(evt);
            }
        });

        PO_Back.setText("Back");
        PO_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(ApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(PO_Back)
                                .addGap(115, 115, 115)
                                .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FM_GreetingLb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(FM_GreetingLb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PO_Back))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FM_StockStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM_StockStatusActionPerformed
        // TODO add your handling code here:
        FM_StockStatus stockstatus = new FM_StockStatus();
        stockstatus.setVisible(true);
    }//GEN-LAST:event_FM_StockStatusActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        fn.PopulatePurchaseOrderTable(PO_Table);
    }//GEN-LAST:event_formComponentShown

    private void ApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveButtonActionPerformed
        // Prompt the user to enter the ID
        String id = JOptionPane.showInputDialog(this, "Enter the ID to approve:", 
                                                "Approve Purchase Order", JOptionPane.PLAIN_MESSAGE);

        if (id != null && !id.trim().isEmpty()) { // Check if ID is entered
            // Call the approvePurchaseOrder method
            fn.approvePurchaseOrder(id.trim(), PO_Table); 
            JOptionPane.showMessageDialog(this, "Purchase Order approved for ID: " + id,
                                          "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No ID entered. Please try again.",
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ApproveButtonActionPerformed

    private void RejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectButtonActionPerformed
        // Prompt the user to enter the ID
        String id = JOptionPane.showInputDialog(this, "Enter the ID to reject:", 
                                                "Reject Purchase Order", JOptionPane.PLAIN_MESSAGE);

        if (id != null && !id.trim().isEmpty()) { // Check if ID is entered
            // Call the approvePurchaseOrder method
            fn.rejectPurchaseOrder(id.trim(), PO_Table); 
            JOptionPane.showMessageDialog(this, "Purchase Order rejected for ID: " + id,
                                          "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No ID entered. Please try again.",
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RejectButtonActionPerformed

    private void PO_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_BackActionPerformed
        this.dispose();
        new FM_MainForm().setVisible(true);
    }//GEN-LAST:event_PO_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FM_VerifyPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FM_VerifyPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FM_VerifyPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FM_VerifyPurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FM_VerifyPurchaseOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveButton;
    private javax.swing.JLabel FM_GreetingLb2;
    private javax.swing.JButton FM_StockStatus;
    private javax.swing.JButton PO_Back;
    private javax.swing.JTable PO_Table;
    private javax.swing.JButton RejectButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
