/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;
import oodj_assignment_functions.Administrator;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class LoginForm extends javax.swing.JFrame {

    public LoginForm() {
        initComponents();
    }
    Administrator adm = new Administrator();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        LoginUsernameLabel = new javax.swing.JPanel();
        Loginlbl = new javax.swing.JLabel();
        Loginbtn = new javax.swing.JButton();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        loginUsername = new javax.swing.JTextField();
        loginPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));

        LoginUsernameLabel.setBackground(new java.awt.Color(204, 204, 204));
        LoginUsernameLabel.setPreferredSize(new java.awt.Dimension(579, 333));

        Loginlbl.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        Loginlbl.setText("Normal Login Page");

        Loginbtn.setText("Login");
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });

        UsernameLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        UsernameLabel.setText("Username");

        PasswordLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        PasswordLabel.setText("Password");

        javax.swing.GroupLayout LoginUsernameLabelLayout = new javax.swing.GroupLayout(LoginUsernameLabel);
        LoginUsernameLabel.setLayout(LoginUsernameLabelLayout);
        LoginUsernameLabelLayout.setHorizontalGroup(
            LoginUsernameLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginUsernameLabelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(LoginUsernameLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginUsernameLabelLayout.createSequentialGroup()
                        .addGroup(LoginUsernameLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLabel)
                            .addComponent(PasswordLabel))
                        .addGap(40, 40, 40)
                        .addGroup(LoginUsernameLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(loginPass))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LoginUsernameLabelLayout.createSequentialGroup()
                        .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 125, Short.MAX_VALUE))))
            .addGroup(LoginUsernameLabelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(Loginlbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LoginUsernameLabelLayout.setVerticalGroup(
            LoginUsernameLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginUsernameLabelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Loginlbl)
                .addGap(44, 44, 44)
                .addGroup(LoginUsernameLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginUsernameLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     
    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        String role = adm.AuthenticateUser(loginUsername.getText(), String.valueOf(loginPass.getPassword()));
        switch(role)
        {
            case "Sales Manager" -> 
            {
                SM_MainPage sm = new SM_MainPage();
                this.dispose();
                sm.setVisible(true);
            }
            case "Purchase Manager" -> 
            {
                PM_MainForm pm = new PM_MainForm(adm.getName());
                this.dispose();
                pm.setVisible(true);
            }
            case "Inventory Manager" -> 
            {
                IM_MainForm im = new IM_MainForm();
                this.dispose();
                im.setVisible(true);
            }
            case "Finance Manager" -> 
            {
                FM_MainForm fm = new FM_MainForm();
                this.dispose();
                fm.setVisible(true);
            }
            case "Administrator" -> 
            {
                AM_MainForm am = new AM_MainForm(adm.getName(), "Administrator");
                this.dispose();
                am.setVisible(true);  
            }
        }
    }//GEN-LAST:event_LoginbtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginUsernameLabel;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JLabel Loginlbl;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel UsernameLabel;
    private java.awt.Canvas canvas1;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JTextField loginUsername;
    // End of variables declaration//GEN-END:variables
}
