/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import oodj_assignment_functions.PurchaseManager;

/**
 *
 * @author Lenovo
 */
public class PM_MainForm extends javax.swing.JFrame {

    static String name;
    public PM_MainForm(String name) {
        initComponents();
        this.name = name;
    }
    PurchaseManager pm = new PurchaseManager();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PM_Panel = new javax.swing.JPanel();
        PM_FunctionPanel = new javax.swing.JPanel();
        PM_ViewSupplierBtn = new javax.swing.JButton();
        PM_ViewItemBtn = new javax.swing.JButton();
        PM_GeneratePurchaseOrderBtn = new javax.swing.JButton();
        PM_LogOutBtn = new javax.swing.JButton();
        PM_GreetingLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PM_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("Purchase Manager"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        PM_Panel.setBackground(new java.awt.Color(153, 153, 153));
        PM_Panel.setName("Purchase Manager Panel"); // NOI18N
        PM_Panel.setPreferredSize(new java.awt.Dimension(1050, 550));

        PM_FunctionPanel.setBackground(new java.awt.Color(204, 204, 204));
        PM_FunctionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Purchase Manager Functionalities", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N
        PM_FunctionPanel.setToolTipText("");
        PM_FunctionPanel.setPreferredSize(new java.awt.Dimension(250, 499));

        PM_ViewSupplierBtn.setBackground(new java.awt.Color(153, 153, 153));
        PM_ViewSupplierBtn.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        PM_ViewSupplierBtn.setText("View List of Suppliers");
        PM_ViewSupplierBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PM_ViewSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PM_ViewSupplierBtnActionPerformed(evt);
            }
        });

        PM_ViewItemBtn.setBackground(new java.awt.Color(153, 153, 153));
        PM_ViewItemBtn.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        PM_ViewItemBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PM_ViewItemBtn.setLabel("View List of Items");
        PM_ViewItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PM_ViewItemBtnActionPerformed(evt);
            }
        });

        PM_GeneratePurchaseOrderBtn.setBackground(new java.awt.Color(153, 153, 153));
        PM_GeneratePurchaseOrderBtn.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        PM_GeneratePurchaseOrderBtn.setText("Generate Purchase Order");
        PM_GeneratePurchaseOrderBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PM_GeneratePurchaseOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PM_GeneratePurchaseOrderBtnActionPerformed(evt);
            }
        });

        PM_LogOutBtn.setBackground(new java.awt.Color(102, 102, 102));
        PM_LogOutBtn.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        PM_LogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment_images/logout.png"))); // NOI18N
        PM_LogOutBtn.setText("Log Out");
        PM_LogOutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PM_LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PM_LogOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PM_FunctionPanelLayout = new javax.swing.GroupLayout(PM_FunctionPanel);
        PM_FunctionPanel.setLayout(PM_FunctionPanelLayout);
        PM_FunctionPanelLayout.setHorizontalGroup(
            PM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PM_FunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PM_ViewItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PM_ViewSupplierBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PM_GeneratePurchaseOrderBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(PM_LogOutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PM_FunctionPanelLayout.setVerticalGroup(
            PM_FunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PM_FunctionPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(PM_ViewItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PM_ViewSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PM_GeneratePurchaseOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PM_LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        PM_GreetingLbl.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        PM_GreetingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PM_GreetingLbl.setText("Welcome, Purchase Manager");
        PM_GreetingLbl.setToolTipText("");
        PM_GreetingLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PM_GreetingLbl.setMaximumSize(new java.awt.Dimension(1050, 50));
        PM_GreetingLbl.setMinimumSize(new java.awt.Dimension(1050, 50));
        PM_GreetingLbl.setName("Welcome Message"); // NOI18N
        PM_GreetingLbl.setPreferredSize(new java.awt.Dimension(1050, 50));

        PM_Table.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PM_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PM_Table.setShowGrid(true);
        jScrollPane1.setViewportView(PM_Table);

        javax.swing.GroupLayout PM_PanelLayout = new javax.swing.GroupLayout(PM_Panel);
        PM_Panel.setLayout(PM_PanelLayout);
        PM_PanelLayout.setHorizontalGroup(
            PM_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PM_GreetingLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PM_PanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PM_FunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PM_PanelLayout.setVerticalGroup(
            PM_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PM_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PM_GreetingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PM_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PM_FunctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PM_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PM_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PM_ViewSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PM_ViewSupplierBtnActionPerformed
        pm.ViewSupplier(PM_Table);
    }//GEN-LAST:event_PM_ViewSupplierBtnActionPerformed

    private void PM_ViewItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PM_ViewItemBtnActionPerformed
        pm.ViewItem(PM_Table);
    }//GEN-LAST:event_PM_ViewItemBtnActionPerformed

    private void PM_GeneratePurchaseOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PM_GeneratePurchaseOrderBtnActionPerformed
        this.dispose();
        new PM_PurchaseOrder().setVisible(true);
    }//GEN-LAST:event_PM_GeneratePurchaseOrderBtnActionPerformed

    private void PM_LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PM_LogOutBtnActionPerformed
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_PM_LogOutBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        PM_GreetingLbl.setText("Welcome, "+ name);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_MainForm(name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PM_FunctionPanel;
    private javax.swing.JButton PM_GeneratePurchaseOrderBtn;
    private javax.swing.JLabel PM_GreetingLbl;
    private javax.swing.JButton PM_LogOutBtn;
    private javax.swing.JPanel PM_Panel;
    private javax.swing.JTable PM_Table;
    private javax.swing.JButton PM_ViewItemBtn;
    private javax.swing.JButton PM_ViewSupplierBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
