/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import javax.swing.JOptionPane;
import oodj_assignment_functions.PurchaseManager;

/**
 *
 * @author Lenovo
 */
public class PM_PurchaseOrder extends javax.swing.JFrame {

    
    public PM_PurchaseOrder() {
        initComponents();
    }
    
    PurchaseManager pm = new PurchaseManager();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PO_Table = new javax.swing.JTable();
        PO_Panel = new javax.swing.JPanel();
        PO_AddPO = new javax.swing.JButton();
        PO_EditPO = new javax.swing.JButton();
        PO_DeletePO = new javax.swing.JButton();
        PO_BackToMain = new javax.swing.JButton();
        PO_ViewReq = new javax.swing.JButton();
        PO_Refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PO_ID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PO_Supplier = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        PO_Item = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PO_Qty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PO_Status = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PO_Price = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PO_PRID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PO_PRDate = new javax.swing.JLabel();
        PO_indicator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 550));

        PO_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PO_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PO_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PO_Table);

        PO_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modify Purchase Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N
        PO_Panel.setToolTipText("");
        PO_Panel.setName(""); // NOI18N

        PO_AddPO.setBackground(new java.awt.Color(153, 153, 153));
        PO_AddPO.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_AddPO.setText("Add Purchase Order");
        PO_AddPO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PO_AddPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_AddPOActionPerformed(evt);
            }
        });

        PO_EditPO.setBackground(new java.awt.Color(153, 153, 153));
        PO_EditPO.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_EditPO.setText("Edit Purchase Order");
        PO_EditPO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PO_EditPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_EditPOActionPerformed(evt);
            }
        });

        PO_DeletePO.setBackground(new java.awt.Color(153, 153, 153));
        PO_DeletePO.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_DeletePO.setText("Delete Purchase Order");
        PO_DeletePO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PO_DeletePO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_DeletePOActionPerformed(evt);
            }
        });

        PO_BackToMain.setBackground(new java.awt.Color(102, 102, 102));
        PO_BackToMain.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_BackToMain.setText("Back");
        PO_BackToMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PO_BackToMain.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment_images/logout.png"))); // NOI18N
        PO_BackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_BackToMainActionPerformed(evt);
            }
        });

        PO_ViewReq.setBackground(new java.awt.Color(153, 153, 153));
        PO_ViewReq.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_ViewReq.setText("View Requisition");
        PO_ViewReq.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PO_ViewReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_ViewReqActionPerformed(evt);
            }
        });

        PO_Refresh.setBackground(new java.awt.Color(153, 153, 153));
        PO_Refresh.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_Refresh.setText("View Purchase Order");
        PO_Refresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PO_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PO_PanelLayout = new javax.swing.GroupLayout(PO_Panel);
        PO_Panel.setLayout(PO_PanelLayout);
        PO_PanelLayout.setHorizontalGroup(
            PO_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PO_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PO_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PO_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PO_EditPO, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PO_AddPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PO_DeletePO, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PO_ViewReq, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PO_BackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PO_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PO_PanelLayout.setVerticalGroup(
            PO_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PO_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PO_AddPO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(PO_EditPO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(PO_DeletePO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(PO_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PO_ViewReq, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PO_BackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("PO ID");

        PO_ID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_ID.setText("poID");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("Supplier");

        PO_Supplier.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("ItemName");

        PO_Item.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        PO_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_ItemActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setText("Quantity");

        PO_Qty.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        PO_Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_QtyActionPerformed(evt);
            }
        });
        PO_Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PO_QtyKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setText("Status");

        PO_Status.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_Status.setText("status");

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("ItemPrice");

        PO_Price.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        PO_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PO_PriceActionPerformed(evt);
            }
        });
        PO_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PO_PriceKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("PR ID");

        PO_PRID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_PRID.setText("prID");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("PR Date");

        PO_PRDate.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_PRDate.setText("PR Date");

        PO_indicator.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        PO_indicator.setText("I");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PO_ID)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PO_Status))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(PO_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PO_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PO_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PO_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PO_PRDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PO_PRID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PO_indicator))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PO_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PO_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PO_ID)
                    .addComponent(jLabel8)
                    .addComponent(PO_Status)
                    .addComponent(jLabel2)
                    .addComponent(PO_PRID)
                    .addComponent(PO_indicator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PO_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(PO_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(PO_PRDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PO_Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(PO_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PO_AddPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_AddPOActionPerformed
        String id = pm.GenerateID();
        String SupplierName = String.valueOf(PO_Supplier.getSelectedItem());
        String ItemName = PO_Item.getText();
        String ItemPrice = String.valueOf(PO_Price.getText());
        String Quantity = String.valueOf(PO_Qty.getText());
        String PRID = PO_PRID.getText();
        pm.generatePurchaseOrder(PRID);
    }//GEN-LAST:event_PO_AddPOActionPerformed

    private void PO_EditPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_EditPOActionPerformed
        String id = PO_ID.getText();
        String SupplierName = String.valueOf(PO_Supplier.getSelectedItem());
        String ItemName = PO_Item.getText();
        String ItemPrice = String.valueOf(PO_Price.getText());
        String Quantity = String.valueOf(PO_Qty.getText());
        if (PO_Item.getText().isEmpty() || PO_Price.getText().isEmpty() || PO_Qty.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "the field cannot be empty");
        }
        else
        {
            pm.EditPO(id, SupplierName, ItemName, ItemPrice, Quantity);
            pm.ViewPO(PO_Table);
            PO_indicator.setText("I");
        }
    }//GEN-LAST:event_PO_EditPOActionPerformed

    private void PO_DeletePOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_DeletePOActionPerformed
        if (PO_Item.getText().isEmpty() || PO_Price.getText().isEmpty() || PO_Qty.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "the field cannot be empty");
        }
        else
        {
            String id = PO_ID.getText();
            pm.DeletePO(id);
            pm.ViewPO(PO_Table);
            PO_indicator.setText("I");
        }
    }//GEN-LAST:event_PO_DeletePOActionPerformed

    private void PO_BackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_BackToMainActionPerformed
        this.dispose();
        new PM_MainForm("Purchase Manager").setVisible(true);
    }//GEN-LAST:event_PO_BackToMainActionPerformed

    private void PO_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PO_ItemActionPerformed

    private void PO_QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PO_QtyActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        pm.ViewPO(PO_Table);
        pm.FillComboBox(PO_Supplier);
    }//GEN-LAST:event_formComponentShown

    private void PO_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PO_PriceActionPerformed

    private void PO_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PO_PriceKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_PO_PriceKeyTyped

    private void PO_QtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PO_QtyKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_PO_QtyKeyTyped

    private void PO_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PO_TableMouseClicked
        int selectedRow = PO_Table.getSelectedRow();
        if (selectedRow != -1)//ensure a row is selected 
        {
            if("l".equals(PO_indicator.getText()))
            {
                PO_PRID.setText(PO_Table.getValueAt(selectedRow, 0).toString());
                PO_PRDate.setText(PO_Table.getValueAt(selectedRow, 3).toString());
            }
            else
            {
            PO_ID.setText(PO_Table.getValueAt(selectedRow, 0).toString());
            PO_Supplier.setSelectedItem(PO_Table.getValueAt(selectedRow, 2).toString());
            PO_Item.setText(PO_Table.getValueAt(selectedRow, 3).toString());
            PO_Price.setText(PO_Table.getValueAt(selectedRow, 4).toString());
            PO_Qty.setText(PO_Table.getValueAt(selectedRow, 5).toString());
            PO_Status.setText(PO_Table.getValueAt(selectedRow, 7).toString());
            }
        }
    }//GEN-LAST:event_PO_TableMouseClicked

    private void PO_ViewReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_ViewReqActionPerformed
        PO_indicator.setText("l");
        pm.ViewPR(PO_Table);
    }//GEN-LAST:event_PO_ViewReqActionPerformed

    private void PO_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PO_RefreshActionPerformed
        PO_indicator.setText("I");
        pm.ViewPO(PO_Table);
    }//GEN-LAST:event_PO_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_PurchaseOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PO_AddPO;
    private javax.swing.JButton PO_BackToMain;
    private javax.swing.JButton PO_DeletePO;
    private javax.swing.JButton PO_EditPO;
    private javax.swing.JLabel PO_ID;
    private javax.swing.JTextField PO_Item;
    private javax.swing.JLabel PO_PRDate;
    private javax.swing.JLabel PO_PRID;
    private javax.swing.JPanel PO_Panel;
    private javax.swing.JTextField PO_Price;
    private javax.swing.JTextField PO_Qty;
    private javax.swing.JButton PO_Refresh;
    private javax.swing.JLabel PO_Status;
    private javax.swing.JComboBox<String> PO_Supplier;
    private javax.swing.JTable PO_Table;
    private javax.swing.JButton PO_ViewReq;
    private javax.swing.JLabel PO_indicator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
