/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

/**
 *
 * @author raida
 */
public class SM_MainPage extends javax.swing.JFrame {

    /**
     * Creates new form SM_MainPage
     */
    public SM_MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSalesItemPage = new javax.swing.JButton();
        BtnStockLevelPage = new javax.swing.JButton();
        BtnProductRequisitionPage = new javax.swing.JButton();
        BtnDailySalesEntryPage = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 0));

        BtnSalesItemPage.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        BtnSalesItemPage.setText("Sales Item");
        BtnSalesItemPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalesItemPageActionPerformed(evt);
            }
        });

        BtnStockLevelPage.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        BtnStockLevelPage.setText("Stock Level");
        BtnStockLevelPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStockLevelPageActionPerformed(evt);
            }
        });

        BtnProductRequisitionPage.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        BtnProductRequisitionPage.setText("Product Requisition");
        BtnProductRequisitionPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductRequisitionPageActionPerformed(evt);
            }
        });

        BtnDailySalesEntryPage.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        BtnDailySalesEntryPage.setText("Daily Sales Entry");
        BtnDailySalesEntryPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDailySalesEntryPageActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        label1.setText("Sales Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnProductRequisitionPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSalesItemPage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnDailySalesEntryPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnStockLevelPage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnSalesItemPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnStockLevelPage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnProductRequisitionPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDailySalesEntryPage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );

        label1.getAccessibleContext().setAccessibleName("Sales Manager");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStockLevelPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStockLevelPageActionPerformed
        this.dispose();
        new SM_StockLevelFrame().setVisible(true);
    }//GEN-LAST:event_BtnStockLevelPageActionPerformed

    private void BtnProductRequisitionPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductRequisitionPageActionPerformed
        this.dispose();
        new SM_PurchaseRequisitionForm().setVisible(true);
    }//GEN-LAST:event_BtnProductRequisitionPageActionPerformed

    private void BtnDailySalesEntryPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDailySalesEntryPageActionPerformed
        this.dispose();
        new SM_SalesEntryForm().setVisible(true);
    }//GEN-LAST:event_BtnDailySalesEntryPageActionPerformed

    private void BtnSalesItemPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalesItemPageActionPerformed
        this.dispose();
        new SM_SalesItemForm().setVisible(true);
    }//GEN-LAST:event_BtnSalesItemPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SM_MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDailySalesEntryPage;
    private javax.swing.JButton BtnProductRequisitionPage;
    private javax.swing.JButton BtnSalesItemPage;
    private javax.swing.JButton BtnStockLevelPage;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
